### ISSUE TITLE
Python 3.8 incompatibility with `read_civis`

### ISSUE THREAD

**Issue by elsander** [civisanalytics/civis-python#370]
Running `civis.io.read_civis` using Python 3.8 raises the following exception:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/miniconda3/envs/survey-toolbox-python/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/miniconda3/envs/survey-toolbox-python/lib/python3.8/site-packages/civis/polling.py", line 44, in run
    poller_result = self.poller(*self.poller_args)
  File "/miniconda3/envs/survey-toolbox-python/lib/python3.8/site-packages/civis/polling.py", line 168, in _check_result
    self._set_api_result(self._last_result)
  File "/miniconda3/envs/survey-toolbox-python/lib/python3.8/site-packages/civis/polling.py", line 182, in _set_api_result
    self.set_result(result)
  File "/miniconda3/envs/survey-toolbox-python/lib/python3.8/concurrent/futures/_base.py", line 524, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
concurrent.futures._base.InvalidStateError: FINISHED: <CivisFuture at 0x10fcd1c40 state=succeeded returned NoneType>
```

Note that this occurs regardless of whether a valid table name is passed in to the function.

**Comment by squidgetx** [comment]
Experiencing the same problem here. in fact it seems that it affects all usages of Civis futures

**Comment by aripollak** [comment]
Looks like this is being worked on in #391.

**Comment by mheilman** [comment]
The master branch should support python 3.8 now after #391, but there hasn't been a release on pypi yet.
